### ISSUE TITLE
pwntool_dbg.py shows the "EOFError" error on split32

### ISSUE THREAD

**Issue by NobinPegasus** [Crypto-Cat/CTF#10]
I'm currently on Kali Linux OS. While I try to run your pwntool_dbg.py on the split32 file it shows the following error:

```
─$ python2 pwntools_dbg.py
[!] Could not populate PLT: invalid syntax (unicorn.py, line 110)
[+] Starting local process './split32': pid 21465
[*] 0x804a018 system
[*] 0x804a030 /bin/cat
[*] Process './split32' stopped with exit code -11 (SIGSEGV) (pid 21465)
[+] Parsing corefile...: Done
[*] '/home/pegasus/Documents/CTF/rop_emporium_all_challenges/rop_emporium/2-split/1-32bit/core.21465'
    Arch:      i386-32-little
    EIP:       0x6161616c
    ESP:       0xffb947d0
    Exe:       '/home/pegasus/Documents/CTF/rop_emporium_all_challenges/rop_emporium/2-split/1-32bit/split32' (0x8048000)
    Fault:     0x6161616c
[*] located EIP offset at 44
[+] Starting local process './split32': pid 21468
Traceback (most recent call last):
  File "pwntools_dbg.py", line 76, in <module>
    flag = io.recvline()
  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 490, in recvline
    return self.recvuntil(self.newline, drop = not keepends, timeout = timeout)
  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 333, in recvuntil
    res = self.recv(timeout=self.timeout)
  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 105, in recv
    return self._recv(numb, timeout) or b''
  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 183, in _recv
    if not self.buffer and not self._fillbuffer(timeout):
  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 154, in _fillbuffer
    data = self.recv_raw(self.buffer.get_fill_size())
  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/process.py", line 686, in recv_raw
    raise EOFError
EOFError
[*] Process './split32' stopped with exit code -11 (SIGSEGV) (pid 21468)
```

Help me resolve it!

**Comment by Crypto-Cat** [comment]
Can you try with python3 and post the output as well?

What OS is your host machine (outside your Kali VM?


-------- Original message --------
From: NobinPegasus ***@***.***>
Date: 19/11/2022 09:05 (GMT+00:00)
To: Crypto-Cat/CTF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Crypto-Cat/CTF] pwntool_dbg.py shows the following error on split32 (Issue #10)

This message is from an external sender. Please take care when responding, clicking links or opening attachments.

I'm currently on Kali Linux OS. While I try to run your pwntool_dbg.py on the split32 file it shows the following error:

─$ python2 pwntools_dbg.py

[!] Could not populate PLT: invalid syntax (unicorn.py, line 110)

[+] Starting local process './split32': pid 21465

[*] 0x804a018 system

[*] 0x804a030 /bin/cat

[*] Process './split32' stopped with exit code -11 (SIGSEGV) (pid 21465)

[+] Parsing corefile...: Done

[*] '/home/pegasus/Documents/CTF/rop_emporium_all_challenges/rop_emporium/2-split/1-32bit/core.21465'

    Arch:      i386-32-little

    EIP:       0x6161616c

    ESP:       0xffb947d0

    Exe:       '/home/pegasus/Documents/CTF/rop_emporium_all_challenges/rop_emporium/2-split/1-32bit/split32' (0x8048000)

    Fault:     0x6161616c

[*] located EIP offset at 44

[+] Starting local process './split32': pid 21468

Traceback (most recent call last):

  File "pwntools_dbg.py", line 76, in <module>

    flag = io.recvline()

  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 490, in recvline

    return self.recvuntil(self.newline, drop = not keepends, timeout = timeout)

  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 333, in recvuntil

    res = self.recv(timeout=self.timeout)

  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 105, in recv

    return self._recv(numb, timeout) or b''

  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 183, in _recv

    if not self.buffer and not self._fillbuffer(timeout):

  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/tube.py", line 154, in _fillbuffer

    data = self.recv_raw(self.buffer.get_fill_size())

  File "/home/pegasus/.local/lib/python2.7/site-packages/pwnlib/tubes/process.py", line 686, in recv_raw

    raise EOFError

EOFError

[*] Process './split32' stopped with exit code -11 (SIGSEGV) (pid 21468)



Help me resolve it!

**Comment by NobinPegasus** [comment]
No I'm not using any VM. It's my host Kali Linux.

With python3 it shows 
```

└─$ python3 pwntools_dbg.py
Traceback (most recent call last):
  File "/home/pegasus/Documents/CTF/rop_emporium_all_challenges/rop_emporium/2-split/1-32bit/pwntools_dbg.py", line 1, in <module>
    from pwn import *
  File "/home/pegasus/.local/lib/python3.10/site-packages/pwn/__init__.py", line 4, in <module>
    from pwn.toplevel import *
  File "/home/pegasus/.local/lib/python3.10/site-packages/pwn/toplevel.py", line 9, in <module>
    import socks
ModuleNotFoundError: No module named 'socks'
```

I had tried to install socks in various ways but failed. That's why installed python2. But the recv shows EOFerror.
 Don't know why.
 
 Also the same errors happen in the autopwn.py script

**Comment by Crypto-Cat** [comment]
Try `pip install PySocks`. It might not be the cause of the issue but you definitely want to use python3.



-------- Original message --------
From: NobinPegasus ***@***.***>
Date: 19/11/2022 09:16 (GMT+00:00)
To: Crypto-Cat/CTF ***@***.***>
Cc: Jonah Burgess ***@***.***>, Comment ***@***.***>
Subject: Re: [Crypto-Cat/CTF] pwntool_dbg.py shows the "EOFError" error on split32 (Issue #10)

This message is from an external sender. Please take care when responding, clicking links or opening attachments.

No I'm not using any VM. It's my host Kali Linux.

With python3 it shows



└─$ python3 pwntools_dbg.py

Traceback (most recent call last):

  File "/home/pegasus/Documents/CTF/rop_emporium_all_challenges/rop_emporium/2-split/1-32bit/pwntools_dbg.py", line 1, in <module>

    from pwn import *

  File "/home/pegasus/.local/lib/python3.10/site-packages/pwn/__init__.py", line 4, in <module>

    from pwn.toplevel import *

  File "/home/pegasus/.local/lib/python3.10/site-packages/pwn/toplevel.py", line 9, in <module>

    import socks

ModuleNotFoundError: No module named 'socks'



I had tried to install socks in various ways but failed. That's why installed python2. But the recv shows EOFerror.
Don't know why.

Also the same errors happen in the autopwn.py script

**Comment by NobinPegasus** [comment]
It shows the following lines:
```

┌──(pegasus㉿pegasus)-[~/…/rop_emporium_all_challenges/rop_emporium/2-split/1-32bit]
└─$ pip install PySocks                                     
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PySocks in /usr/lib/python3/dist-packages (1.7.1)
                                                                                                                                
┌──(pegasus㉿pegasus)-[~/…/rop_emporium_all_challenges/rop_emporium/2-split/1-32bit]
└─$ pip3 install PySocks
Collecting PySocks
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Installing collected packages: PySocks
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pwntools 4.8.0 requires capstone>=3.0.5rc2, which is not installed.
pwntools 4.8.0 requires mako>=1.0.0, which is not installed.
pwntools 4.8.0 requires packaging, which is not installed.
pwntools 4.8.0 requires paramiko>=1.15.2, which is not installed.
pwntools 4.8.0 requires psutil>=3.3.0, which is not installed.
pwntools 4.8.0 requires pyelftools>=0.2.4, which is not installed.
pwntools 4.8.0 requires pygments>=2.0, which is not installed.
pwntools 4.8.0 requires pyserial>=2.7, which is not installed.
pwntools 4.8.0 requires requests>=2.0, which is not installed.
pwntools 4.8.0 requires ropgadget>=5.3, which is not installed.
pwntools 4.8.0 requires six>=1.12.0, which is not installed.
pwntools 4.8.0 requires sortedcontainers, which is not installed.
pwntools 4.8.0 requires unicorn>=1.0.2rc1, which is not installed.
Successfully installed PySocks-1.7.1
```

**Comment by Crypto-Cat** [comment]
Try to install all those missing dependencies, installation instructions here: https://github.com/Gallopsled/pwntools#installation

**Comment by NobinPegasus** [comment]
Thanks it works for python3 now.

**Comment by Crypto-Cat** [comment]
Excellent! 🙂
