### ISSUE TITLE
Issue with Pivot 32bit code

### ISSUE THREAD

**Issue by sparky23172** [Crypto-Cat/CTF#2]
Hello,

While going through your videos, I discovered an issue on Lines 115. It looks like io.recvlines(2) needs to be io.recvlines(5) for the code to work  

https://github.com/Crypto-Cat/CTF/blob/main/pwn/rop_emporium/7-pivot/1-32bit/pwntools_dbg.py#L115

**Comment by Crypto-Cat** [comment]
hi mate, not sure what the reason is for that 🤔 i just tested the script again locally and for me it only works with io.recvlines(2), if i change to io.recvlines(5) i dont get the flag 😆 

are you running in python3? the rest of the script is unaltered?

**Comment by sparky23172** [comment]
So sorry! 
Yesterday it wasn't working after I was going through it for an hour or two. It seems to be completely fine now!
