### ISSUE TITLE
Could find another way to contact you:: Is this normal?

### ISSUE THREAD

**Issue by Bryan-netizen** [Crypto-Cat/CTF#4]
![cryptocat](https://user-images.githubusercontent.com/68712272/156410938-d0138299-ee04-4bb0-b8e6-57dca72c870a.png)

**Comment by Crypto-Cat** [comment]
It's OK, if you click it you will go through to a confirmation page you will (hopefully) need permissions to commit. Had to double check myself for a second there 😅 TY 💜
