### ISSUE TITLE
Remote 'g' packet reply is too long

### ISSUE THREAD

**Issue by galaxy3000** [Crypto-Cat/CTF#5]
when i use the debug，gdb.debug(), it reply Remote 'g' packet reply is too long, I try in ubuntu 16.04 and ubuntu 20.04，gdb 8.2 and 11.2 ,python2 and python3 , the problem is exist,thank you

**Comment by Crypto-Cat** [comment]
Check this thread: https://stackoverflow.com/a/18680319
