### ISSUE TITLE
Ghidra cheat sheet link

### ISSUE THREAD

**Issue by donotdox** [Crypto-Cat/CTF#9]
Hi,

Wasn't sure how best to contact so opened as issue.

I think the link to the Ghidra cheat sheet should be https://ghidra-sre.org/CheatSheet.html

Thanks!

**Comment by Crypto-Cat** [comment]
Aghhhh links keep changing! At least this one isn't redirecting to dodgy shop for steroids, like the dvwa one was xD ty 💜
